default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  host: localhost
  username: pguser
  password: pguser

development:
  <<: *default
  database: support_development_db

test:
  <<: *default
  database: support_test_db

production:
  <<: *default
  database: support_production_db
